title: Pet Friendly
short_description: PetFriendly um submódulo de StreetPet
description: >- # this means to ignore newlines until "baseurl:"
  Um projeto desenvolvido pela Equipe StreetPet. 
baseurl: "/"

# google services
ganalytics: UA-156621148-2
gtagmanager:
gmapsapikey: AIzaSyDxbkicoGy26nUK4NdjILbxzPQcLEc3sTQ

# facebook
fpixel:

# collections
collections:
  main:
    output: true
    permalink: /main/:name

  defaults:
  - scope:
      path: 'assets/images'
      type: 'main'
  values:
    image: true

# contacts
address:
phone:
email: petfriendly@carlosdelfino.eti.br
  
# social
twitter:
facebook: PetFriendly-103816844510377
instagram:
linkedin:
youtube:
googleplus:
github: github.com/streetpet
dribbble:

# copyright
owner: streetpet.app.web
